version: '3.3'

services:
  app_server:
    build: dev-ops/docker/containers/app
    links:
      - app_mysql:mysql
    extra_hosts:
      - "docker.vm:127.0.0.1"
    volumes:
      - shopware_projectdata:/app
  app_mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app

  data:
    build: dev-ops/docker/containers/ssh
    container_name: shopware_data
    image: data
    volumes:
      - shopware_projectdata:/app
    ports:
      - "2222:22"
volumes:
  shopware_projectdata:
    external: true