version: '3.3'

services:
  app_server:
    build: dev-ops/docker/containers/app
    container_name: shopware_app
    links:
      - app_mysql:mysql
    extra_hosts:
      - "docker.vm:127.0.0.1"
    volumes:
      - shopware_projectdata:/app
  app_mysql:
    build: dev-ops/docker/containers/mysql
    container_name: shopware_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
  data:
    build: dev-ops/docker/containers/ssh
    container_name: shopware_data
    image: data
    volumes:
      - shopware_projectdata:/app
    ports:
      - "2222:22"
  redis:
    image: redis:3.2.11
    container_name: shopware_redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
  redisui:
    image: tenstartups/redis-commander
    container_name: shopware_redisui
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"
  rabbitmq:
    image: rabbitmq:3.7.3-management
    container_name: shopware_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 15672:15672
volumes:
  shopware_projectdata:
    external: true
