#override defaults for dev
version: "3.3"

services:
  app_server:
    environment:
      CONTAINER_UID: __USER_ID__
      APPLICATION_UID: __USER_ID__
      APPLICATION_GID: __GROUP_ID__

  app_mysql:
    tmpfs:
    - /mysql-data